model:
  base_learning_rate: 1.0e-5
  target: sgm.models.diffusion.DiffusionEngine
  params:
    scale_factor: 0.18215
    disable_first_stage_autocast: False
    ckpt_path: checkpoints/svd_3d_9input.safetensors
    en_and_decode_n_samples_a_time: 10
    exclude_wrap_input: [fps_id, motion_bucket_id, indices_3d, num_video_frames, num_video_frames_3d, index]

    scheduler_config:
      target: sgm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 400 ]
        cycle_lengths: [ 10000000000000 ]
        f_start: [ 6.e-7 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.Denoiser
      params:
        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.VScalingWithEDMcNoise

    network_config:
      target: sgm.modules.diffusionmodules.video_model.VideoUNet
      params:
        adm_in_channels_3d: 1280
        in_channels_3d: 8
        adm_in_channels: 768
        num_classes: sequential
        use_checkpoint: True
        in_channels: 9
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        spatial_transformer_attn_type: softmax-xformers
        extra_ff_mix_layer: True
        use_spatial_context: True
        merge_strategy: learned_with_images
        video_kernel_size: [ 3, 1, 1 ]

    conditioner_config:
      target: sgm.modules.GeneralConditioner
      params:
        emb_models:
          - is_trainable: False
            target: sgm.modules.encoders.modules.AttnEmbedder
            input_key: cond_frames_without_noise
            ucg_rate: 0.2
            params:
              model_config:
                target: sgm.modules.encoders.modules.FrozenOpenCLIPImagePredictionEmbedder
                params:
                  n_cond_frames: 1
                  n_copies: 1
                  open_clip_embedding_config:
                    target: sgm.modules.encoders.modules.FrozenOpenCLIPImageEmbedder
                    params:
                      freeze: True

          - input_key: fps_id
            is_trainable: False
            target: sgm.modules.encoders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256

          - input_key: motion_bucket_id
            is_trainable: False
            target: sgm.modules.encoders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256

          - input_key: cond_frames
            is_trainable: False
            target: sgm.modules.encoders.modules.VideoPredictionEmbedderWithEncoder
            ucg_rate: 0.2
            params:
              disable_encoder_autocast: False
              en_and_decode_n_samples_a_time: 10
              n_cond_frames: 1
              n_copies: 1
              is_ae: True
              encoder_config:
                target: sgm.models.autoencoder.AutoencoderKLModeOnly
                params:
                  embed_dim: 4
                  monitor: val/rec_loss
                  ddconfig:
                    attn_type: vanilla-xformers
                    double_z: True
                    z_channels: 4
                    resolution: 256
                    in_channels: 3
                    out_ch: 3
                    ch: 128
                    ch_mult: [ 1, 2, 4, 4 ]
                    num_res_blocks: 2
                    attn_resolutions: [ ]
                    dropout: 0.0
                  lossconfig:
                    target: torch.nn.Identity

          - input_key: cond_aug
            is_trainable: False
            target: sgm.modules.encoders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256

          - input_key: mask_concat
            is_trainable: False
            target: sgm.modules.encoders.modules.ConcatIdentity

          - input_key: depth
            is_trainable: True
            target: sgm.modules.encoders.modules.DepthEmbedder
            params:
              input_channels: 6

    conditioner_3d_config:
      target: sgm.modules.GeneralConditioner
      params:
        emb_models:
        - is_trainable: False
          target: sgm.modules.encoders.modules.AttnEmbedder3D
          input_key: cond_frames_without_noise_3d
          params:
            model_config:
              target: sgm.modules.encoders.modules.FrozenOpenCLIPImagePredictionEmbedder
              params:
                n_cond_frames: 1
                n_copies: 1
                open_clip_embedding_config:
                  target: sgm.modules.encoders.modules.FrozenOpenCLIPImageEmbedder
                  params:
                    freeze: True

        - input_key: cond_frames_3d
          is_trainable: False
          target: sgm.modules.encoders.modules.VideoPredictionEmbedderWithEncoder3D
          params:
            disable_encoder_autocast: False
            n_cond_frames: 1
            n_copies: 1
            is_ae: True
            encoder_config:
              target: sgm.models.autoencoder.AutoencoderKLModeOnly
              params:
                embed_dim: 4
                monitor: val/rec_loss
                ddconfig:
                  attn_type: vanilla-xformers
                  double_z: True
                  z_channels: 4
                  resolution: 256
                  in_channels: 3
                  out_ch: 3
                  ch: 128
                  ch_mult: [1, 2, 4, 4]
                  num_res_blocks: 2
                  attn_resolutions: []
                  dropout: 0.0
                lossconfig:
                  target: torch.nn.Identity

        - input_key: cond_aug_3d
          is_trainable: False
          target: sgm.modules.encoders.modules.ConcatTimestepEmbedderND
          params:
            outdim: 256

        - input_key: polars_rad_3d
          is_trainable: False
          target: sgm.modules.encoders.modules.ConcatTimestepEmbedderND
          params:
            outdim: 512

        - input_key: azimuths_rad_3d
          is_trainable: False
          target: sgm.modules.encoders.modules.ConcatTimestepEmbedderND
          params:
            outdim: 512

    first_stage_config:
      target: sgm.models.autoencoder.AutoencodingEngine
      params:
        loss_config:
          target: torch.nn.Identity
        regularizer_config:
          target: sgm.modules.autoencoding.regularizers.DiagonalGaussianRegularizer
        encoder_config:
          target: sgm.modules.diffusionmodules.model.Encoder
          params:
            attn_type: vanilla
            double_z: True
            z_channels: 4
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [ 1, 2, 4, 4 ]
            num_res_blocks: 2
            attn_resolutions: [ ]
            dropout: 0.0
        decoder_config:
          target: sgm.modules.autoencoding.temporal_ae.VideoDecoder
          params:
            attn_type: vanilla
            double_z: True
            z_channels: 4
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [ 1, 2, 4, 4 ]
            num_res_blocks: 2
            attn_resolutions: [ ]
            dropout: 0.0
            video_kernel_size: [ 3, 1, 1 ]

    loss_fn_config:
      target: sgm.modules.diffusionmodules.loss.StandardDiffusionLoss
      params:
        reweight: 5.0
        batch2model_keys: [ image_only_indicator, num_video_frames, image_only_indicator_3d, num_video_frames_3d, indices_3d, obj_pos, mask_fuse, valid_mask, obj_ratio ]
        loss_weighting_config:
          target: sgm.modules.diffusionmodules.loss_weighting.EDMWeighting
          params:
            sigma_data: 1.0
        sigma_sampler_config:
          target: sgm.modules.diffusionmodules.sigma_sampling.EDMSampling
          params:
            p_mean: 1.2
            p_std: 1.6

    sampler_config:
      target: sgm.modules.diffusionmodules.sampling.EulerEDMSampler
      params:
        num_steps: 20
        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.EDMDiscretization
          params:
            sigma_max: 700.0

        guider_config:
          target: sgm.modules.diffusionmodules.guiders.LinearPredictionGuider
          params:
            max_scale: 2.0
            min_scale: 1.2
            num_frames: 10

        guider_3d_config:
          target: sgm.modules.diffusionmodules.guiders.TrianglePredictionGuider
          params:
            max_scale: 2.5
            num_frames: 21

    optimizer_config:
      target: deepspeed.ops.adam.FusedAdam

data:
  target: sgm.data.nus.NuScenesLoader
  params:
    num_frames: 10
    out_size: [ 576, 1024 ]
    num_workers: 8
    batch_size: 1
    fps_id: 10


lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 5000

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_epochs: 1

    image_logger:
      target: main.ImageLogger
      params:
        disabled: False
        enable_autocast: True
        batch_frequency: 200
        max_images: 64
        increase_log_steps: False
        log_first_step: False
        log_images_kwargs:
          use_ema_scope: False
          N: 64
          n_rows: 8
          ucg_keys: [ cond_frames, cond_frames_without_noise, cond_frames_3d, cond_frames_without_noise_3d ]
          sampling_keys: [ image_only_indicator, num_video_frames, image_only_indicator_3d, num_video_frames_3d, indices_3d, obj_pos, mask_fuse, valid_mask, obj_ratio ]

  trainer:
    devices: 0, 1, 2, 3, 4, 5, 6, 7
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    max_epochs: 8
    precision: 16-mixed
    strategy: deepspeed_stage_2